# Generated by Django 5.1.3 on 2024-11-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Transaction ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('transaction_date', models.DateField(verbose_name='Transaction Date')),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'permissions': [('can_read', 'Can Read Transactions'), ('can_update', 'Can Update Transactions'), ('can_delete', 'Can Delete Transactions'), ('can_create', 'Can Create Transactions')],
            },
        ),
    ]
